version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/defense
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: defense
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  model-server:
    build: ./model-server
    ports:
      - "11434:11434"

  linux-scanner:
    build: ./linux-scanner
    environment:
      BACKEND_URL: http://backend:8000
      SCAN_INTERVAL: 600   # seconds between scans
    volumes:
      - /var/log:/var/log:ro          # host logs (read-only)
      - /mnt/c:/mnt/c:ro              # OPTIONAL: scan Windows drive (if WSL)
      - ./rules:/rules:ro             # YARA rules directory
      - ./suricata:/etc/suricata:ro   # optional Suricata config
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "bridge"
    depends_on:
      - backend

volumes:
  db_data:

