apiVersion: v1
kind: Namespace
metadata:
  name: ai-defend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scanner-config
  namespace: ai-defend
data:
  scan-config.json: |
    {
      "scan_mode": "network",
      "api_url": "http://backend-service:8000/events",
      "scanners": ["nmap"],
      "nmap": {
        "targets": ["10.0.0.0/24"],
        "ports": "1-1000",
        "arguments": "-T4 -sV"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-agent
  namespace: ai-defend
  labels:
    app: scanner
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scanner
      component: agent
  template:
    metadata:
      labels:
        app: scanner
        component: agent
    spec:
      serviceAccountName: scanner-sa
      hostNetwork: true  # Allows network scanning
      containers:
      - name: scanner
        image: ai-defend-scanner:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: "http://backend-service:8000/events"
        - name: SCAN_MODE
          value: "network"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config
          mountPath: /etc/scanner
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
          readOnlyRootFilesystem: false
      volumes:
      - name: config
        configMap:
          name: scanner-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-sa
  namespace: ai-defend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scanner-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scanner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scanner-role
subjects:
- kind: ServiceAccount
  name: scanner-sa
  namespace: ai-defend
